approvedGitRepositories:
  - "**"

catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.2.7
  vite-plus: 0.2.7
  vitest: 4.1.10

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - vitest
  - "@vitest/*"
