approvedGitRepositories:
  - "**"

catalog:
  vite: "npm:@voidzero-dev/vite-plus-core@latest"
  vite-plus: latest
  vitest: 4.1.9

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - vitest
  - "@vitest/*"
