catalog:
  '@jnana-app/kit': 'https://packages.r2.jnana.app/jnana-app-kit/jnana-app-kit-0.0.7-af2fc8cdac0c8d2ed46a21a927ee911f.tgz'
  vite: npm:@voidzero-dev/vite-plus-core@0.2.9
  vite-plus: 0.2.9
  vitest: 4.1.10

compressionLevel: mixed

enableGlobalCache: false

enableScripts: false

nodeLinker: node-modules

npmMinimalAgeGate: 0

npmPreapprovedPackages:
  - vitest
  - "@vitest/*"
